#!/bin/sh
#
# this hook replace version in nodistract.user.js
#
# To enable this hook, rename this file to "pre-commit".

VERSION=$(git log --pretty=oneline src/nodistract.user.js | wc -l | tr -d ' ')
sed -i -e "s/\(\/\/ @version[ ]*[0-9]\.[0-9]*\)\.[0-9]*/\1.$VERSION/" src/nodistract.user.js 
